"""create priority table

Revision ID: 5b8fc1b1edd1
Revises: be396d7d2018
Create Date: 2021-06-24 20:15:52.626446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8fc1b1edd1'
down_revision = 'be396d7d2018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority',
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('priority_id')
    )
    op.add_column('task', sa.Column('priority_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'priority', ['priority_id'], ['priority_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'priority_id')
    op.drop_table('priority')
    # ### end Alembic commands ###
