"""add task isCompleted column

Revision ID: 74a447f5f7f3
Revises: 5b8fc1b1edd1
Create Date: 2021-07-02 08:21:44.395448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a447f5f7f3'
down_revision = '5b8fc1b1edd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_status')
    op.add_column('task', sa.Column('isCompleted', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'task', 'priority', ['priority_id'], ['priority_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'isCompleted')
    op.create_table('task_status',
    sa.Column('status_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('status_id')
    )
    # ### end Alembic commands ###
